import { F1CalendarRace } from "./f1-data-constants";

export interface F1CalendarLinks {
  year: number;
  ical?: string;
  gcal?: string;
  note?: string;
}

export const F1_CALENDAR_LINKS: F1CalendarLinks[] = [
  {
    year: 2026,
    ical: "webcal://files.formula1.com/ics/formula1.ics",
    gcal: "https://calendar.google.com/calendar/r?cid=webcal%3A%2F%2Ffiles.formula1.com%2Fics%2Fformula1.ics",
    note: "Formula 1 Official (2026)",
  },
  // 2027+: add here each season
];

export function getCalendarLinksForYear(year: number): F1CalendarLinks | undefined {
  return F1_CALENDAR_LINKS.find(l => l.year === year);
}

export const F1_2025_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Australia", officialName: "Formula 1 Rolex Australian Grand Prix 2025", circuit: "Albert Park Circuit", city: "Melbourne", dates: "14 - 16 Mar", raceDate: "Mar 16", hasSprint: false, slug: "australia", utcOffset: 11, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 2, country: "China", officialName: "Formula 1 Heineken Chinese Grand Prix 2025", circuit: "Shanghai International Circuit", city: "Shanghai", dates: "21 - 23 Mar", raceDate: "Mar 23", hasSprint: true, slug: "china", utcOffset: 8, raceStartLocal: "15:00", qualiStartLocal: "15:00", sprintStartLocal: "11:00" },
  { round: 3, country: "Japan", officialName: "Formula 1 Aramco Japanese Grand Prix 2025", circuit: "Suzuka International Racing Course", city: "Suzuka", dates: "04 - 06 Apr", raceDate: "Apr 6", hasSprint: false, slug: "japan", utcOffset: 9, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 4, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2025", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "11 - 13 Apr", raceDate: "Apr 13", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:00", qualiStartLocal: "19:00" },
  { round: 5, country: "Saudi Arabia", officialName: "Formula 1 STC Saudi Arabian Grand Prix 2025", circuit: "Jeddah Corniche Circuit", city: "Jeddah", dates: "18 - 20 Apr", raceDate: "Apr 20", hasSprint: false, slug: "saudi-arabia", utcOffset: 3, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 6, country: "Miami", officialName: "Formula 1 Crypto.com Miami Grand Prix 2025", circuit: "Miami International Autodrome", city: "Miami", dates: "02 - 04 May", raceDate: "May 4", hasSprint: true, slug: "miami", utcOffset: -4, raceStartLocal: "16:00", qualiStartLocal: "17:00", sprintStartLocal: "13:00" },
  { round: 7, country: "Emilia Romagna", officialName: "Formula 1 AWS Gran Premio del Made in Italy 2025", circuit: "Autodromo Enzo e Dino Ferrari", city: "Imola", dates: "16 - 18 May", raceDate: "May 18", hasSprint: false, slug: "emilia-romagna", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 8, country: "Monaco", officialName: "Formula 1 Tag Heuer Monaco Grand Prix 2025", circuit: "Circuit de Monaco", city: "Monte Carlo", dates: "23 - 25 May", raceDate: "May 25", hasSprint: false, slug: "monaco", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 9, country: "Spain", officialName: "Formula 1 Aramco Gran Premio de Espana 2025", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "30 May - 01 Jun", raceDate: "Jun 1", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 10, country: "Canada", officialName: "Formula 1 Pirelli Grand Prix du Canada 2025", circuit: "Circuit Gilles Villeneuve", city: "Montreal", dates: "13 - 15 Jun", raceDate: "Jun 15", hasSprint: false, slug: "canada", utcOffset: -4, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 11, country: "Austria", officialName: "Formula 1 MSC Cruises Austrian Grand Prix 2025", circuit: "Red Bull Ring", city: "Spielberg", dates: "27 - 29 Jun", raceDate: "Jun 29", hasSprint: false, slug: "austria", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 12, country: "Britain", officialName: "Formula 1 Qatar Airways British Grand Prix 2025", circuit: "Silverstone Circuit", city: "Silverstone", dates: "04 - 06 Jul", raceDate: "Jul 6", hasSprint: false, slug: "great-britain", utcOffset: 1, raceStartLocal: "16:00", qualiStartLocal: "16:00" },
  { round: 13, country: "Belgium", officialName: "Formula 1 Rolex Belgian Grand Prix 2025", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "25 - 27 Jul", raceDate: "Jul 27", hasSprint: true, slug: "belgium", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "12:00" },
  { round: 14, country: "Hungary", officialName: "Formula 1 Magyar Nagydij 2025", circuit: "Hungaroring", city: "Budapest", dates: "01 - 03 Aug", raceDate: "Aug 3", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 15, country: "Netherlands", officialName: "Formula 1 Heineken Dutch Grand Prix 2025", circuit: "Circuit Zandvoort", city: "Zandvoort", dates: "29 - 31 Aug", raceDate: "Aug 31", hasSprint: false, slug: "netherlands", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 16, country: "Italy", officialName: "Formula 1 Pirelli Gran Premio d Italia 2025", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "05 - 07 Sep", raceDate: "Sep 7", hasSprint: false, slug: "italy", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 17, country: "Azerbaijan", officialName: "Formula 1 Qatar Airways Azerbaijan Grand Prix 2025", circuit: "Baku City Circuit", city: "Baku", dates: "19 - 21 Sep", raceDate: "Sep 21", hasSprint: false, slug: "azerbaijan", utcOffset: 4, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 18, country: "Singapore", officialName: "Formula 1 Singapore Airlines Singapore Grand Prix 2025", circuit: "Marina Bay Street Circuit", city: "Singapore", dates: "03 - 05 Oct", raceDate: "Oct 5", hasSprint: false, slug: "singapore", utcOffset: 8, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 19, country: "United States", officialName: "Formula 1 MSC Cruises United States Grand Prix 2025", circuit: "Circuit of The Americas", city: "Austin", dates: "17 - 19 Oct", raceDate: "Oct 19", hasSprint: true, slug: "united-states", utcOffset: -5, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "13:00" },
  { round: 20, country: "Mexico", officialName: "Formula 1 Gran Premio de la Ciudad de Mexico 2025", circuit: "Autodromo Hermanos Rodriguez", city: "Mexico City", dates: "24 - 26 Oct", raceDate: "Oct 26", hasSprint: false, slug: "mexico", utcOffset: -6, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 21, country: "Brazil", officialName: "Formula 1 MSC Cruises Grande Premio de Sao Paulo 2025", circuit: "Autodromo Jose Carlos Pace", city: "Sao Paulo", dates: "07 - 09 Nov", raceDate: "Nov 9", hasSprint: true, slug: "brazil", utcOffset: -3, raceStartLocal: "14:00", qualiStartLocal: "15:00", sprintStartLocal: "11:00" },
  { round: 22, country: "Las Vegas", officialName: "Formula 1 Heineken Las Vegas Grand Prix 2025", circuit: "Las Vegas Strip Circuit", city: "Las Vegas", dates: "20 - 22 Nov", raceDate: "Nov 22", hasSprint: false, slug: "las-vegas", utcOffset: -8, raceStartLocal: "22:00", qualiStartLocal: "22:00" },
  { round: 23, country: "Qatar", officialName: "Formula 1 Qatar Airways Qatar Grand Prix 2025", circuit: "Lusail International Circuit", city: "Lusail", dates: "28 - 30 Nov", raceDate: "Nov 30", hasSprint: true, slug: "qatar", utcOffset: 3, raceStartLocal: "19:00", qualiStartLocal: "21:00", sprintStartLocal: "17:00" },
  { round: 24, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2025", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "05 - 07 Dec", raceDate: "Dec 7", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:00", qualiStartLocal: "18:00" },
];

export const F1_2024_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2024", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "29 Feb - 02 Mar", raceDate: "Mar 2", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:00", qualiStartLocal: "19:00" },
  { round: 2, country: "Saudi Arabia", officialName: "Formula 1 STC Saudi Arabian Grand Prix 2024", circuit: "Jeddah Corniche Circuit", city: "Jeddah", dates: "07 - 09 Mar", raceDate: "Mar 9", hasSprint: false, slug: "saudi-arabia", utcOffset: 3, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 3, country: "Australia", officialName: "Formula 1 Rolex Australian Grand Prix 2024", circuit: "Albert Park Circuit", city: "Melbourne", dates: "22 - 24 Mar", raceDate: "Mar 24", hasSprint: false, slug: "australia", utcOffset: 11, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 4, country: "Japan", officialName: "Formula 1 Lenovo Japanese Grand Prix 2024", circuit: "Suzuka International Racing Course", city: "Suzuka", dates: "05 - 07 Apr", raceDate: "Apr 7", hasSprint: false, slug: "japan", utcOffset: 9, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 5, country: "China", officialName: "Formula 1 Lenovo Chinese Grand Prix 2024", circuit: "Shanghai International Circuit", city: "Shanghai", dates: "19 - 21 Apr", raceDate: "Apr 21", hasSprint: true, slug: "china", utcOffset: 8, raceStartLocal: "15:00", qualiStartLocal: "15:00", sprintStartLocal: "11:00" },
  { round: 6, country: "Miami", officialName: "Formula 1 Crypto.com Miami Grand Prix 2024", circuit: "Miami International Autodrome", city: "Miami", dates: "03 - 05 May", raceDate: "May 5", hasSprint: true, slug: "miami", utcOffset: -4, raceStartLocal: "16:00", qualiStartLocal: "17:00", sprintStartLocal: "13:00" },
  { round: 7, country: "Emilia Romagna", officialName: "Formula 1 MSC Cruises Gran Premio del Made in Italy 2024", circuit: "Autodromo Enzo e Dino Ferrari", city: "Imola", dates: "17 - 19 May", raceDate: "May 19", hasSprint: false, slug: "emilia-romagna", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 8, country: "Monaco", officialName: "Formula 1 Grand Prix de Monaco 2024", circuit: "Circuit de Monaco", city: "Monte Carlo", dates: "23 - 26 May", raceDate: "May 26", hasSprint: false, slug: "monaco", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 9, country: "Canada", officialName: "Formula 1 AWS Grand Prix du Canada 2024", circuit: "Circuit Gilles Villeneuve", city: "Montreal", dates: "07 - 09 Jun", raceDate: "Jun 9", hasSprint: false, slug: "canada", utcOffset: -4, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 10, country: "Spain", officialName: "Formula 1 Aramco Gran Premio de Espana 2024", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "21 - 23 Jun", raceDate: "Jun 23", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 11, country: "Austria", officialName: "Formula 1 Qatar Airways Austrian Grand Prix 2024", circuit: "Red Bull Ring", city: "Spielberg", dates: "28 - 30 Jun", raceDate: "Jun 30", hasSprint: false, slug: "austria", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 12, country: "Britain", officialName: "Formula 1 Qatar Airways British Grand Prix 2024", circuit: "Silverstone Circuit", city: "Silverstone", dates: "05 - 07 Jul", raceDate: "Jul 7", hasSprint: false, slug: "great-britain", utcOffset: 1, raceStartLocal: "16:00", qualiStartLocal: "16:00" },
  { round: 13, country: "Hungary", officialName: "Formula 1 Hungarian Grand Prix 2024", circuit: "Hungaroring", city: "Budapest", dates: "19 - 21 Jul", raceDate: "Jul 21", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 14, country: "Belgium", officialName: "Formula 1 Rolex Belgian Grand Prix 2024", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "26 - 28 Jul", raceDate: "Jul 28", hasSprint: false, slug: "belgium", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 15, country: "Netherlands", officialName: "Formula 1 Heineken Dutch Grand Prix 2024", circuit: "Circuit Zandvoort", city: "Zandvoort", dates: "23 - 25 Aug", raceDate: "Aug 25", hasSprint: false, slug: "netherlands", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 16, country: "Italy", officialName: "Formula 1 Pirelli Gran Premio d Italia 2024", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "30 Aug - 01 Sep", raceDate: "Sep 1", hasSprint: false, slug: "italy", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 17, country: "Azerbaijan", officialName: "Formula 1 Qatar Airways Azerbaijan Grand Prix 2024", circuit: "Baku City Circuit", city: "Baku", dates: "13 - 15 Sep", raceDate: "Sep 15", hasSprint: false, slug: "azerbaijan", utcOffset: 4, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 18, country: "Singapore", officialName: "Formula 1 Singapore Airlines Singapore Grand Prix 2024", circuit: "Marina Bay Street Circuit", city: "Singapore", dates: "20 - 22 Sep", raceDate: "Sep 22", hasSprint: false, slug: "singapore", utcOffset: 8, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 19, country: "United States", officialName: "Formula 1 Pirelli United States Grand Prix 2024", circuit: "Circuit of The Americas", city: "Austin", dates: "18 - 20 Oct", raceDate: "Oct 20", hasSprint: true, slug: "united-states", utcOffset: -5, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "13:00" },
  { round: 20, country: "Mexico", officialName: "Formula 1 Gran Premio de la Ciudad de Mexico 2024", circuit: "Autodromo Hermanos Rodriguez", city: "Mexico City", dates: "25 - 27 Oct", raceDate: "Oct 27", hasSprint: false, slug: "mexico", utcOffset: -6, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 21, country: "Brazil", officialName: "Formula 1 Lenovo Grande Premio de Sao Paulo 2024", circuit: "Autodromo Jose Carlos Pace", city: "Sao Paulo", dates: "01 - 03 Nov", raceDate: "Nov 3", hasSprint: true, slug: "brazil", utcOffset: -3, raceStartLocal: "14:00", qualiStartLocal: "15:00", sprintStartLocal: "11:00" },
  { round: 22, country: "Las Vegas", officialName: "Formula 1 Heineken Silver Las Vegas Grand Prix 2024", circuit: "Las Vegas Strip Circuit", city: "Las Vegas", dates: "21 - 23 Nov", raceDate: "Nov 23", hasSprint: false, slug: "las-vegas", utcOffset: -8, raceStartLocal: "22:00", qualiStartLocal: "22:00" },
  { round: 23, country: "Qatar", officialName: "Formula 1 Qatar Airways Qatar Grand Prix 2024", circuit: "Lusail International Circuit", city: "Lusail", dates: "29 Nov - 01 Dec", raceDate: "Dec 1", hasSprint: true, slug: "qatar", utcOffset: 3, raceStartLocal: "19:00", qualiStartLocal: "21:00", sprintStartLocal: "17:00" },
  { round: 24, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2024", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "06 - 08 Dec", raceDate: "Dec 8", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:00", qualiStartLocal: "18:00" },
];

export const F1_2023_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2023", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "02 - 05 Mar", raceDate: "Mar 5", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:00", qualiStartLocal: "19:00" },
  { round: 2, country: "Saudi Arabia", officialName: "Formula 1 STC Saudi Arabian Grand Prix 2023", circuit: "Jeddah Corniche Circuit", city: "Jeddah", dates: "17 - 19 Mar", raceDate: "Mar 19", hasSprint: false, slug: "saudi-arabia", utcOffset: 3, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 3, country: "Australia", officialName: "Formula 1 Rolex Australian Grand Prix 2023", circuit: "Albert Park Circuit", city: "Melbourne", dates: "30 Mar - 02 Apr", raceDate: "Apr 2", hasSprint: false, slug: "australia", utcOffset: 11, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 4, country: "Azerbaijan", officialName: "Formula 1 Azerbaijan Grand Prix 2023", circuit: "Baku City Circuit", city: "Baku", dates: "28 - 30 Apr", raceDate: "Apr 30", hasSprint: true, slug: "azerbaijan", utcOffset: 4, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "11:30" },
  { round: 5, country: "Miami", officialName: "Formula 1 Crypto.com Miami Grand Prix 2023", circuit: "Miami International Autodrome", city: "Miami", dates: "05 - 07 May", raceDate: "May 7", hasSprint: false, slug: "miami", utcOffset: -4, raceStartLocal: "16:00", qualiStartLocal: "17:00" },
  { round: 6, country: "Monaco", officialName: "Formula 1 Grand Prix de Monaco 2023", circuit: "Circuit de Monaco", city: "Monte Carlo", dates: "26 - 28 May", raceDate: "May 28", hasSprint: false, slug: "monaco", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 7, country: "Spain", officialName: "Formula 1 AWS Gran Premio de Espana 2023", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "02 - 04 Jun", raceDate: "Jun 4", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 8, country: "Canada", officialName: "Formula 1 Pirelli Grand Prix du Canada 2023", circuit: "Circuit Gilles Villeneuve", city: "Montreal", dates: "16 - 18 Jun", raceDate: "Jun 18", hasSprint: false, slug: "canada", utcOffset: -4, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 9, country: "Austria", officialName: "Formula 1 Rolex Austrian Grand Prix 2023", circuit: "Red Bull Ring", city: "Spielberg", dates: "30 Jun - 02 Jul", raceDate: "Jul 2", hasSprint: false, slug: "austria", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 10, country: "Britain", officialName: "Formula 1 Aramco British Grand Prix 2023", circuit: "Silverstone Circuit", city: "Silverstone", dates: "07 - 09 Jul", raceDate: "Jul 9", hasSprint: false, slug: "great-britain", utcOffset: 1, raceStartLocal: "16:00", qualiStartLocal: "16:00" },
  { round: 11, country: "Hungary", officialName: "Formula 1 Qatar Airways Hungarian Grand Prix 2023", circuit: "Hungaroring", city: "Budapest", dates: "21 - 23 Jul", raceDate: "Jul 23", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 12, country: "Belgium", officialName: "Formula 1 MSC Cruises Belgian Grand Prix 2023", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "28 - 30 Jul", raceDate: "Jul 30", hasSprint: false, slug: "belgium", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 13, country: "Netherlands", officialName: "Formula 1 Heineken Dutch Grand Prix 2023", circuit: "Circuit Zandvoort", city: "Zandvoort", dates: "25 - 27 Aug", raceDate: "Aug 27", hasSprint: false, slug: "netherlands", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 14, country: "Italy", officialName: "Formula 1 Pirelli Gran Premio d Italia 2023", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "01 - 03 Sep", raceDate: "Sep 3", hasSprint: false, slug: "italy", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 15, country: "Singapore", officialName: "Formula 1 Singapore Airlines Singapore Grand Prix 2023", circuit: "Marina Bay Street Circuit", city: "Singapore", dates: "15 - 17 Sep", raceDate: "Sep 17", hasSprint: false, slug: "singapore", utcOffset: 8, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 16, country: "Japan", officialName: "Formula 1 Lenovo Japanese Grand Prix 2023", circuit: "Suzuka International Racing Course", city: "Suzuka", dates: "22 - 24 Sep", raceDate: "Sep 24", hasSprint: false, slug: "japan", utcOffset: 9, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 17, country: "Qatar", officialName: "Formula 1 Qatar Airways Qatar Grand Prix 2023", circuit: "Lusail International Circuit", city: "Lusail", dates: "06 - 08 Oct", raceDate: "Oct 8", hasSprint: true, slug: "qatar", utcOffset: 3, raceStartLocal: "19:00", qualiStartLocal: "21:00", sprintStartLocal: "17:00" },
  { round: 18, country: "United States", officialName: "Formula 1 Lenovo United States Grand Prix 2023", circuit: "Circuit of The Americas", city: "Austin", dates: "20 - 22 Oct", raceDate: "Oct 22", hasSprint: true, slug: "united-states", utcOffset: -5, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "13:00" },
  { round: 19, country: "Mexico", officialName: "Formula 1 Gran Premio de la Ciudad de Mexico 2023", circuit: "Autodromo Hermanos Rodriguez", city: "Mexico City", dates: "27 - 29 Oct", raceDate: "Oct 29", hasSprint: false, slug: "mexico", utcOffset: -6, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 20, country: "Brazil", officialName: "Formula 1 Rolex Grande Premio de Sao Paulo 2023", circuit: "Autodromo Jose Carlos Pace", city: "Sao Paulo", dates: "03 - 05 Nov", raceDate: "Nov 5", hasSprint: true, slug: "brazil", utcOffset: -3, raceStartLocal: "14:00", qualiStartLocal: "15:00", sprintStartLocal: "11:00" },
  { round: 21, country: "Las Vegas", officialName: "Formula 1 Heineken Silver Las Vegas Grand Prix 2023", circuit: "Las Vegas Strip Circuit", city: "Las Vegas", dates: "16 - 18 Nov", raceDate: "Nov 18", hasSprint: false, slug: "las-vegas", utcOffset: -8, raceStartLocal: "22:00", qualiStartLocal: "22:00" },
  { round: 22, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2023", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "24 - 26 Nov", raceDate: "Nov 26", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:00", qualiStartLocal: "18:00" },
];

export const F1_2022_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2022", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "18 - 20 Mar", raceDate: "Mar 20", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:00", qualiStartLocal: "19:00" },
  { round: 2, country: "Saudi Arabia", officialName: "Formula 1 STC Saudi Arabian Grand Prix 2022", circuit: "Jeddah Corniche Circuit", city: "Jeddah", dates: "25 - 27 Mar", raceDate: "Mar 27", hasSprint: false, slug: "saudi-arabia", utcOffset: 3, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 3, country: "Australia", officialName: "Formula 1 Rolex Australian Grand Prix 2022", circuit: "Albert Park Circuit", city: "Melbourne", dates: "08 - 10 Apr", raceDate: "Apr 10", hasSprint: false, slug: "australia", utcOffset: 11, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 4, country: "Emilia Romagna", officialName: "Formula 1 Rolex Gran Premio del Made in Italy 2022", circuit: "Autodromo Enzo e Dino Ferrari", city: "Imola", dates: "22 - 24 Apr", raceDate: "Apr 24", hasSprint: true, slug: "emilia-romagna", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "15:30" },
  { round: 5, country: "Miami", officialName: "Formula 1 Crypto.com Miami Grand Prix 2022", circuit: "Miami International Autodrome", city: "Miami", dates: "06 - 08 May", raceDate: "May 8", hasSprint: false, slug: "miami", utcOffset: -4, raceStartLocal: "16:30", qualiStartLocal: "17:00" },
  { round: 6, country: "Spain", officialName: "Formula 1 Aramco Gran Premio de Espana 2022", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "20 - 22 May", raceDate: "May 22", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 7, country: "Monaco", officialName: "Formula 1 Grand Prix de Monaco 2022", circuit: "Circuit de Monaco", city: "Monte Carlo", dates: "27 - 29 May", raceDate: "May 29", hasSprint: false, slug: "monaco", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 8, country: "Azerbaijan", officialName: "Formula 1 Azerbaijan Grand Prix 2022", circuit: "Baku City Circuit", city: "Baku", dates: "10 - 12 Jun", raceDate: "Jun 12", hasSprint: false, slug: "azerbaijan", utcOffset: 4, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 9, country: "Canada", officialName: "Formula 1 AWS Grand Prix du Canada 2022", circuit: "Circuit Gilles Villeneuve", city: "Montreal", dates: "17 - 19 Jun", raceDate: "Jun 19", hasSprint: false, slug: "canada", utcOffset: -4, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 10, country: "Britain", officialName: "Formula 1 Lenovo British Grand Prix 2022", circuit: "Silverstone Circuit", city: "Silverstone", dates: "01 - 03 Jul", raceDate: "Jul 3", hasSprint: false, slug: "great-britain", utcOffset: 1, raceStartLocal: "16:00", qualiStartLocal: "16:00" },
  { round: 11, country: "Austria", officialName: "Formula 1 Rolex Austrian Grand Prix 2022", circuit: "Red Bull Ring", city: "Spielberg", dates: "08 - 10 Jul", raceDate: "Jul 10", hasSprint: true, slug: "austria", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "16:30" },
  { round: 12, country: "France", officialName: "Formula 1 Lenovo Grand Prix de France 2022", circuit: "Circuit Paul Ricard", city: "Le Castellet", dates: "22 - 24 Jul", raceDate: "Jul 24", hasSprint: false, slug: "france", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 13, country: "Hungary", officialName: "Formula 1 Hungarian Grand Prix 2022", circuit: "Hungaroring", city: "Budapest", dates: "29 - 31 Jul", raceDate: "Jul 31", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 14, country: "Belgium", officialName: "Formula 1 Rolex Belgian Grand Prix 2022", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "26 - 28 Aug", raceDate: "Aug 28", hasSprint: false, slug: "belgium", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 15, country: "Netherlands", officialName: "Formula 1 Heineken Dutch Grand Prix 2022", circuit: "Circuit Zandvoort", city: "Zandvoort", dates: "02 - 04 Sep", raceDate: "Sep 4", hasSprint: false, slug: "netherlands", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 16, country: "Italy", officialName: "Formula 1 Pirelli Gran Premio d Italia 2022", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "09 - 11 Sep", raceDate: "Sep 11", hasSprint: false, slug: "italy", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 17, country: "Singapore", officialName: "Formula 1 Singapore Airlines Singapore Grand Prix 2022", circuit: "Marina Bay Street Circuit", city: "Singapore", dates: "30 Sep - 02 Oct", raceDate: "Oct 2", hasSprint: false, slug: "singapore", utcOffset: 8, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 18, country: "Japan", officialName: "Formula 1 Honda Japanese Grand Prix 2022", circuit: "Suzuka International Racing Course", city: "Suzuka", dates: "07 - 09 Oct", raceDate: "Oct 9", hasSprint: false, slug: "japan", utcOffset: 9, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 19, country: "United States", officialName: "Formula 1 Aramco United States Grand Prix 2022", circuit: "Circuit of The Americas", city: "Austin", dates: "20 - 23 Oct", raceDate: "Oct 23", hasSprint: false, slug: "united-states", utcOffset: -5, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 20, country: "Mexico", officialName: "Formula 1 Gran Premio de la Ciudad de Mexico 2022", circuit: "Autodromo Hermanos Rodriguez", city: "Mexico City", dates: "28 - 30 Oct", raceDate: "Oct 30", hasSprint: false, slug: "mexico", utcOffset: -6, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 21, country: "Brazil", officialName: "Formula 1 Heineken Grande Premio do Brasil 2022", circuit: "Autodromo Jose Carlos Pace", city: "Sao Paulo", dates: "11 - 13 Nov", raceDate: "Nov 13", hasSprint: true, slug: "brazil", utcOffset: -3, raceStartLocal: "14:00", qualiStartLocal: "15:00", sprintStartLocal: "15:30" },
  { round: 22, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2022", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "18 - 20 Nov", raceDate: "Nov 20", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:00", qualiStartLocal: "18:00" },
];

export const F1_2021_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2021", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "26 - 28 Mar", raceDate: "Mar 28", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:00", qualiStartLocal: "19:00" },
  { round: 2, country: "Emilia Romagna", officialName: "Formula 1 Pirelli Gran Premio del Made in Italy 2021", circuit: "Autodromo Enzo e Dino Ferrari", city: "Imola", dates: "16 - 18 Apr", raceDate: "Apr 18", hasSprint: false, slug: "emilia-romagna", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 3, country: "Portugal", officialName: "Formula 1 Heineken Grande Premio de Portugal 2021", circuit: "Algarve International Circuit", city: "Portimao", dates: "30 Apr - 02 May", raceDate: "May 2", hasSprint: false, slug: "portugal", utcOffset: 1, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 4, country: "Spain", officialName: "Formula 1 AWS Gran Premio de Espana 2021", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "07 - 09 May", raceDate: "May 9", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 5, country: "Monaco", officialName: "Formula 1 Grand Prix de Monaco 2021", circuit: "Circuit de Monaco", city: "Monte Carlo", dates: "20 - 23 May", raceDate: "May 23", hasSprint: false, slug: "monaco", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 6, country: "Azerbaijan", officialName: "Formula 1 Azerbaijan Grand Prix 2021", circuit: "Baku City Circuit", city: "Baku", dates: "04 - 06 Jun", raceDate: "Jun 6", hasSprint: false, slug: "azerbaijan", utcOffset: 4, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 7, country: "France", officialName: "Formula 1 Emirates Grand Prix de France 2021", circuit: "Circuit Paul Ricard", city: "Le Castellet", dates: "18 - 20 Jun", raceDate: "Jun 20", hasSprint: false, slug: "france", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 8, country: "Austria", officialName: "Formula 1 Pirelli Grosser Preis der Steiermark 2021", circuit: "Red Bull Ring", city: "Spielberg", dates: "25 - 27 Jun", raceDate: "Jun 27", hasSprint: false, slug: "styria", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 9, country: "Austria", officialName: "Formula 1 Rolex Grosser Preis von Osterreich 2021", circuit: "Red Bull Ring", city: "Spielberg", dates: "02 - 04 Jul", raceDate: "Jul 4", hasSprint: false, slug: "austria", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 10, country: "Britain", officialName: "Formula 1 Pirelli British Grand Prix 2021", circuit: "Silverstone Circuit", city: "Silverstone", dates: "16 - 18 Jul", raceDate: "Jul 18", hasSprint: true, slug: "great-britain", utcOffset: 1, raceStartLocal: "16:00", qualiStartLocal: "16:00", sprintStartLocal: "16:30" },
  { round: 11, country: "Hungary", officialName: "Formula 1 Magyar Nagydij 2021", circuit: "Hungaroring", city: "Budapest", dates: "30 Jul - 01 Aug", raceDate: "Aug 1", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 12, country: "Belgium", officialName: "Formula 1 Rolex Belgian Grand Prix 2021", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "27 - 29 Aug", raceDate: "Aug 29", hasSprint: false, slug: "belgium", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 13, country: "Netherlands", officialName: "Formula 1 Heineken Dutch Grand Prix 2021", circuit: "Circuit Zandvoort", city: "Zandvoort", dates: "03 - 05 Sep", raceDate: "Sep 5", hasSprint: false, slug: "netherlands", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 14, country: "Italy", officialName: "Formula 1 Heineken Gran Premio d Italia 2021", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "10 - 12 Sep", raceDate: "Sep 12", hasSprint: true, slug: "italy", utcOffset: 2, raceStartLocal: "15:00", qualiStartLocal: "16:00", sprintStartLocal: "16:30" },
  { round: 15, country: "Russia", officialName: "Formula 1 VTB Russian Grand Prix 2021", circuit: "Sochi Autodrom", city: "Sochi", dates: "24 - 26 Sep", raceDate: "Sep 26", hasSprint: false, slug: "russia", utcOffset: 3, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 16, country: "Turkey", officialName: "Formula 1 Rolex Turkish Grand Prix 2021", circuit: "Istanbul Park", city: "Istanbul", dates: "08 - 10 Oct", raceDate: "Oct 10", hasSprint: false, slug: "turkey", utcOffset: 3, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 17, country: "United States", officialName: "Formula 1 Aramco United States Grand Prix 2021", circuit: "Circuit of The Americas", city: "Austin", dates: "22 - 24 Oct", raceDate: "Oct 24", hasSprint: false, slug: "united-states", utcOffset: -5, raceStartLocal: "15:00", qualiStartLocal: "16:00" },
  { round: 18, country: "Mexico", officialName: "Formula 1 Gran Premio de la Ciudad de Mexico 2021", circuit: "Autodromo Hermanos Rodriguez", city: "Mexico City", dates: "29 - 31 Oct", raceDate: "Oct 31", hasSprint: false, slug: "mexico", utcOffset: -6, raceStartLocal: "14:00", qualiStartLocal: "15:00" },
  { round: 19, country: "Brazil", officialName: "Formula 1 Heineken Grande Premio do Brasil 2021", circuit: "Autodromo Jose Carlos Pace", city: "Sao Paulo", dates: "05 - 07 Nov", raceDate: "Nov 7", hasSprint: true, slug: "brazil", utcOffset: -3, raceStartLocal: "14:00", qualiStartLocal: "15:00", sprintStartLocal: "15:30" },
  { round: 20, country: "Qatar", officialName: "Formula 1 Ooredoo Qatar Grand Prix 2021", circuit: "Lusail International Circuit", city: "Lusail", dates: "19 - 21 Nov", raceDate: "Nov 21", hasSprint: false, slug: "qatar", utcOffset: 3, raceStartLocal: "18:00", qualiStartLocal: "19:00" },
  { round: 21, country: "Saudi Arabia", officialName: "Formula 1 stc Saudi Arabian Grand Prix 2021", circuit: "Jeddah Corniche Circuit", city: "Jeddah", dates: "03 - 05 Dec", raceDate: "Dec 5", hasSprint: false, slug: "saudi-arabia", utcOffset: 3, raceStartLocal: "20:00", qualiStartLocal: "21:00" },
  { round: 22, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2021", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "10 - 12 Dec", raceDate: "Dec 12", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:00", qualiStartLocal: "18:00" },
];

export const F1_2020_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Austria", officialName: "Formula 1 Rolex Grosser Preis von Osterreich 2020", circuit: "Red Bull Ring", city: "Spielberg", dates: "03 - 05 Jul", raceDate: "Jul 5", hasSprint: false, slug: "austria", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 2, country: "Austria", officialName: "Formula 1 Pirelli Grosser Preis der Steiermark 2020", circuit: "Red Bull Ring", city: "Spielberg", dates: "10 - 12 Jul", raceDate: "Jul 12", hasSprint: false, slug: "styria", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 3, country: "Hungary", officialName: "Formula 1 Rolex Magyar Nagydij 2020", circuit: "Hungaroring", city: "Budapest", dates: "17 - 19 Jul", raceDate: "Jul 19", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 4, country: "Britain", officialName: "Formula 1 Pirelli British Grand Prix 2020", circuit: "Silverstone Circuit", city: "Silverstone", dates: "31 Jul - 02 Aug", raceDate: "Aug 2", hasSprint: false, slug: "great-britain", utcOffset: 1, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 5, country: "Britain", officialName: "Formula 1 Qatar Airways 70th Anniversary Grand Prix 2020", circuit: "Silverstone Circuit", city: "Silverstone", dates: "07 - 09 Aug", raceDate: "Aug 9", hasSprint: false, slug: "70th-anniversary", utcOffset: 1, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 6, country: "Spain", officialName: "Formula 1 Gran Premio de Espana 2020", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "14 - 16 Aug", raceDate: "Aug 16", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 7, country: "Belgium", officialName: "Formula 1 Rolex Belgian Grand Prix 2020", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "28 - 30 Aug", raceDate: "Aug 30", hasSprint: false, slug: "belgium", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 8, country: "Italy", officialName: "Formula 1 Heineken Gran Premio d Italia 2020", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "04 - 06 Sep", raceDate: "Sep 6", hasSprint: false, slug: "italy", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 9, country: "Tuscany", officialName: "Formula 1 Heineken Gran Premio della Toscana Ferrari 1000 2020", circuit: "Mugello Circuit", city: "Mugello", dates: "11 - 13 Sep", raceDate: "Sep 13", hasSprint: false, slug: "tuscany", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 10, country: "Russia", officialName: "Formula 1 VTB Russian Grand Prix 2020", circuit: "Sochi Autodrom", city: "Sochi", dates: "25 - 27 Sep", raceDate: "Sep 27", hasSprint: false, slug: "russia", utcOffset: 3, raceStartLocal: "13:10", qualiStartLocal: "14:00" },
  { round: 11, country: "Eifel", officialName: "Formula 1 Aramco Eifel Grand Prix 2020", circuit: "Nurburgring", city: "Nurburg", dates: "09 - 11 Oct", raceDate: "Oct 11", hasSprint: false, slug: "eifel", utcOffset: 2, raceStartLocal: "13:10", qualiStartLocal: "14:00" },
  { round: 12, country: "Portugal", officialName: "Formula 1 Heineken Grande Premio de Portugal 2020", circuit: "Algarve International Circuit", city: "Portimao", dates: "23 - 25 Oct", raceDate: "Oct 25", hasSprint: false, slug: "portugal", utcOffset: 1, raceStartLocal: "14:10", qualiStartLocal: "15:00" },
  { round: 13, country: "Emilia Romagna", officialName: "Formula 1 Pirelli Gran Premio dell Emilia Romagna 2020", circuit: "Autodromo Enzo e Dino Ferrari", city: "Imola", dates: "31 Oct - 01 Nov", raceDate: "Nov 1", hasSprint: false, slug: "emilia-romagna", utcOffset: 1, raceStartLocal: "13:10", qualiStartLocal: "14:00" },
  { round: 14, country: "Turkey", officialName: "Formula 1 DHL Turkish Grand Prix 2020", circuit: "Istanbul Park", city: "Istanbul", dates: "13 - 15 Nov", raceDate: "Nov 15", hasSprint: false, slug: "turkey", utcOffset: 3, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 15, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2020", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "27 - 29 Nov", raceDate: "Nov 29", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:10", qualiStartLocal: "18:00" },
  { round: 16, country: "Bahrain", officialName: "Formula 1 Rolex Sakhir Grand Prix 2020", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "04 - 06 Dec", raceDate: "Dec 6", hasSprint: false, slug: "sakhir", utcOffset: 3, raceStartLocal: "18:10", qualiStartLocal: "18:00" },
  { round: 17, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2020", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "11 - 13 Dec", raceDate: "Dec 13", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:10", qualiStartLocal: "17:00" },
];

export const F1_2019_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Australia", officialName: "Formula 1 Rolex Australian Grand Prix 2019", circuit: "Albert Park Circuit", city: "Melbourne", dates: "14 - 17 Mar", raceDate: "Mar 17", hasSprint: false, slug: "australia", utcOffset: 11, raceStartLocal: "16:10", qualiStartLocal: "16:00" },
  { round: 2, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2019", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "29 - 31 Mar", raceDate: "Mar 31", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:10", qualiStartLocal: "18:00" },
  { round: 3, country: "China", officialName: "Formula 1 Heineken Chinese Grand Prix 2019", circuit: "Shanghai International Circuit", city: "Shanghai", dates: "12 - 14 Apr", raceDate: "Apr 14", hasSprint: false, slug: "china", utcOffset: 8, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 4, country: "Azerbaijan", officialName: "Formula 1 Azerbaijan Grand Prix 2019", circuit: "Baku City Circuit", city: "Baku", dates: "26 - 28 Apr", raceDate: "Apr 28", hasSprint: false, slug: "azerbaijan", utcOffset: 4, raceStartLocal: "16:10", qualiStartLocal: "15:00" },
  { round: 5, country: "Spain", officialName: "Formula 1 Gran Premio de Espana 2019", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "10 - 12 May", raceDate: "May 12", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 6, country: "Monaco", officialName: "Formula 1 Grand Prix de Monaco 2019", circuit: "Circuit de Monaco", city: "Monte Carlo", dates: "23 - 26 May", raceDate: "May 26", hasSprint: false, slug: "monaco", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 7, country: "Canada", officialName: "Formula 1 Grand Prix du Canada 2019", circuit: "Circuit Gilles Villeneuve", city: "Montreal", dates: "07 - 09 Jun", raceDate: "Jun 9", hasSprint: false, slug: "canada", utcOffset: -4, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 8, country: "France", officialName: "Formula 1 Pirelli Grand Prix de France 2019", circuit: "Circuit Paul Ricard", city: "Le Castellet", dates: "21 - 23 Jun", raceDate: "Jun 23", hasSprint: false, slug: "france", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 9, country: "Austria", officialName: "Formula 1 Myworld Motorrad Grosser Preis von Osterreich 2019", circuit: "Red Bull Ring", city: "Spielberg", dates: "28 - 30 Jun", raceDate: "Jun 30", hasSprint: false, slug: "austria", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 10, country: "Britain", officialName: "Formula 1 Rolex British Grand Prix 2019", circuit: "Silverstone Circuit", city: "Silverstone", dates: "11 - 14 Jul", raceDate: "Jul 14", hasSprint: false, slug: "great-britain", utcOffset: 1, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 11, country: "Germany", officialName: "Formula 1 Grosser Preis von Deutschland 2019", circuit: "Hockenheimring", city: "Hockenheim", dates: "26 - 28 Jul", raceDate: "Jul 28", hasSprint: false, slug: "germany", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 12, country: "Hungary", officialName: "Formula 1 Rolex Magyar Nagydij 2019", circuit: "Hungaroring", city: "Budapest", dates: "02 - 04 Aug", raceDate: "Aug 4", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 13, country: "Belgium", officialName: "Formula 1 Rolex Belgian Grand Prix 2019", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "30 Aug - 01 Sep", raceDate: "Sep 1", hasSprint: false, slug: "belgium", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 14, country: "Italy", officialName: "Formula 1 Heineken Italian Grand Prix 2019", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "06 - 08 Sep", raceDate: "Sep 8", hasSprint: false, slug: "italy", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 15, country: "Singapore", officialName: "Formula 1 Singapore Airlines Singapore Grand Prix 2019", circuit: "Marina Bay Street Circuit", city: "Singapore", dates: "20 - 22 Sep", raceDate: "Sep 22", hasSprint: false, slug: "singapore", utcOffset: 8, raceStartLocal: "20:10", qualiStartLocal: "21:00" },
  { round: 16, country: "Russia", officialName: "Formula 1 VTB Russian Grand Prix 2019", circuit: "Sochi Autodrom", city: "Sochi", dates: "27 - 29 Sep", raceDate: "Sep 29", hasSprint: false, slug: "russia", utcOffset: 3, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 17, country: "Japan", officialName: "Formula 1 Japanese Grand Prix 2019", circuit: "Suzuka International Racing Course", city: "Suzuka", dates: "11 - 13 Oct", raceDate: "Oct 13", hasSprint: false, slug: "japan", utcOffset: 9, raceStartLocal: "14:10", qualiStartLocal: "15:00" },
  { round: 18, country: "Mexico", officialName: "Formula 1 Gran Premio de Mexico 2019", circuit: "Autodromo Hermanos Rodriguez", city: "Mexico City", dates: "25 - 27 Oct", raceDate: "Oct 27", hasSprint: false, slug: "mexico", utcOffset: -6, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 19, country: "United States", officialName: "Formula 1 United States Grand Prix 2019", circuit: "Circuit of The Americas", city: "Austin", dates: "01 - 03 Nov", raceDate: "Nov 3", hasSprint: false, slug: "united-states", utcOffset: -5, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 20, country: "Brazil", officialName: "Formula 1 Heineken Grande Premio do Brasil 2019", circuit: "Autodromo Jose Carlos Pace", city: "Sao Paulo", dates: "15 - 17 Nov", raceDate: "Nov 17", hasSprint: false, slug: "brazil", utcOffset: -3, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 21, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2019", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "28 Nov - 01 Dec", raceDate: "Dec 1", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:10", qualiStartLocal: "17:00" },
];

export const F1_2018_CALENDAR_DATA: F1CalendarRace[] = [
  { round: 1, country: "Australia", officialName: "Formula 1 Rolex Australian Grand Prix 2018", circuit: "Albert Park Circuit", city: "Melbourne", dates: "22 - 25 Mar", raceDate: "Mar 25", hasSprint: false, slug: "australia", utcOffset: 11, raceStartLocal: "16:10", qualiStartLocal: "16:00" },
  { round: 2, country: "Bahrain", officialName: "Formula 1 Gulf Air Bahrain Grand Prix 2018", circuit: "Bahrain International Circuit", city: "Sakhir", dates: "06 - 08 Apr", raceDate: "Apr 8", hasSprint: false, slug: "bahrain", utcOffset: 3, raceStartLocal: "18:10", qualiStartLocal: "18:00" },
  { round: 3, country: "China", officialName: "Formula 1 Heineken Chinese Grand Prix 2018", circuit: "Shanghai International Circuit", city: "Shanghai", dates: "13 - 15 Apr", raceDate: "Apr 15", hasSprint: false, slug: "china", utcOffset: 8, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 4, country: "Azerbaijan", officialName: "Formula 1 Azerbaijan Grand Prix 2018", circuit: "Baku City Circuit", city: "Baku", dates: "27 - 29 Apr", raceDate: "Apr 29", hasSprint: false, slug: "azerbaijan", utcOffset: 4, raceStartLocal: "16:10", qualiStartLocal: "15:00" },
  { round: 5, country: "Spain", officialName: "Formula 1 Gran Premio de Espana 2018", circuit: "Circuit de Barcelona-Catalunya", city: "Barcelona", dates: "11 - 13 May", raceDate: "May 13", hasSprint: false, slug: "spain", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 6, country: "Monaco", officialName: "Formula 1 Grand Prix de Monaco 2018", circuit: "Circuit de Monaco", city: "Monte Carlo", dates: "24 - 27 May", raceDate: "May 27", hasSprint: false, slug: "monaco", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 7, country: "Canada", officialName: "Formula 1 Grand Prix du Canada 2018", circuit: "Circuit Gilles Villeneuve", city: "Montreal", dates: "08 - 10 Jun", raceDate: "Jun 10", hasSprint: false, slug: "canada", utcOffset: -4, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 8, country: "France", officialName: "Formula 1 Pirelli Grand Prix de France 2018", circuit: "Circuit Paul Ricard", city: "Le Castellet", dates: "22 - 24 Jun", raceDate: "Jun 24", hasSprint: false, slug: "france", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 9, country: "Austria", officialName: "Formula 1 Rolex Grosser Preis von Osterreich 2018", circuit: "Red Bull Ring", city: "Spielberg", dates: "29 Jun - 01 Jul", raceDate: "Jul 1", hasSprint: false, slug: "austria", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 10, country: "Britain", officialName: "Formula 1 Rolex British Grand Prix 2018", circuit: "Silverstone Circuit", city: "Silverstone", dates: "06 - 08 Jul", raceDate: "Jul 8", hasSprint: false, slug: "great-britain", utcOffset: 1, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 11, country: "Germany", officialName: "Formula 1 Grosser Preis von Deutschland 2018", circuit: "Hockenheimring", city: "Hockenheim", dates: "20 - 22 Jul", raceDate: "Jul 22", hasSprint: false, slug: "germany", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 12, country: "Hungary", officialName: "Formula 1 Rolex Magyar Nagydij 2018", circuit: "Hungaroring", city: "Budapest", dates: "27 - 29 Jul", raceDate: "Jul 29", hasSprint: false, slug: "hungary", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 13, country: "Belgium", officialName: "Formula 1 Rolex Belgian Grand Prix 2018", circuit: "Circuit de Spa-Francorchamps", city: "Spa", dates: "24 - 26 Aug", raceDate: "Aug 26", hasSprint: false, slug: "belgium", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 14, country: "Italy", officialName: "Formula 1 Heineken Italian Grand Prix 2018", circuit: "Autodromo Nazionale Monza", city: "Monza", dates: "31 Aug - 02 Sep", raceDate: "Sep 2", hasSprint: false, slug: "italy", utcOffset: 2, raceStartLocal: "15:10", qualiStartLocal: "15:00" },
  { round: 15, country: "Singapore", officialName: "Formula 1 Singapore Airlines Singapore Grand Prix 2018", circuit: "Marina Bay Street Circuit", city: "Singapore", dates: "14 - 16 Sep", raceDate: "Sep 16", hasSprint: false, slug: "singapore", utcOffset: 8, raceStartLocal: "20:10", qualiStartLocal: "21:00" },
  { round: 16, country: "Russia", officialName: "Formula 1 VTB Russian Grand Prix 2018", circuit: "Sochi Autodrom", city: "Sochi", dates: "28 - 30 Sep", raceDate: "Sep 30", hasSprint: false, slug: "russia", utcOffset: 3, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 17, country: "Japan", officialName: "Formula 1 Japanese Grand Prix 2018", circuit: "Suzuka International Racing Course", city: "Suzuka", dates: "05 - 07 Oct", raceDate: "Oct 7", hasSprint: false, slug: "japan", utcOffset: 9, raceStartLocal: "14:10", qualiStartLocal: "15:00" },
  { round: 18, country: "United States", officialName: "Formula 1 United States Grand Prix 2018", circuit: "Circuit of The Americas", city: "Austin", dates: "19 - 21 Oct", raceDate: "Oct 21", hasSprint: false, slug: "united-states", utcOffset: -5, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 19, country: "Mexico", officialName: "Formula 1 Gran Premio de Mexico 2018", circuit: "Autodromo Hermanos Rodriguez", city: "Mexico City", dates: "25 - 28 Oct", raceDate: "Oct 28", hasSprint: false, slug: "mexico", utcOffset: -6, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 20, country: "Brazil", officialName: "Formula 1 Heineken Grande Premio do Brasil 2018", circuit: "Autodromo Jose Carlos Pace", city: "Sao Paulo", dates: "09 - 11 Nov", raceDate: "Nov 11", hasSprint: false, slug: "brazil", utcOffset: -3, raceStartLocal: "14:10", qualiStartLocal: "14:00" },
  { round: 21, country: "Abu Dhabi", officialName: "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2018", circuit: "Yas Marina Circuit", city: "Abu Dhabi", dates: "22 - 25 Nov", raceDate: "Nov 25", hasSprint: false, slug: "abu-dhabi", utcOffset: 4, raceStartLocal: "17:10", qualiStartLocal: "17:00" },
];

export function getCalendarForYear(year: number): F1CalendarRace[] | null {
  switch (year) {
    case 2018: return F1_2018_CALENDAR_DATA;
    case 2019: return F1_2019_CALENDAR_DATA;
    case 2020: return F1_2020_CALENDAR_DATA;
    case 2021: return F1_2021_CALENDAR_DATA;
    case 2022: return F1_2022_CALENDAR_DATA;
    case 2023: return F1_2023_CALENDAR_DATA;
    case 2024: return F1_2024_CALENDAR_DATA;
    case 2025: return F1_2025_CALENDAR_DATA;
    default: return null;
  }
}