// 2026 F1 Calendar Data & Trigger Definitions

export interface F1CalendarRace {
  round: number;
  country: string;
  officialName: string;
  circuit: string;
  city: string;
  dates: string;
  raceDate: string;
  hasSprint: boolean;
  slug: string;
  utcOffset: number;
  raceStartLocal: string;
  qualiStartLocal: string;
  sprintStartLocal?: string;
  cancelled?: boolean;
  results?: any[];
  /** formula1.com meeting id used for /en/results/{year}/races/{meetingId}/{f1Slug}/... */
  meetingId?: number;
  /** formula1.com slug, only when it differs from our own slug */
  f1Slug?: string;
}

export interface TriggerType {
  id: string;
  label: string;
  sessionName: string;
  sprintOnly?: boolean;
}

export const F1_2026_CALENDAR: F1CalendarRace[] = [
  {
    round: 1,
    country: "Australia",
    officialName: "FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX 2026",
    circuit: "Albert Park Circuit",
    city: "Melbourne",
    dates: "06 - 08 Mar",
    raceDate: "Mar 8",
    hasSprint: false,
    slug: "australia",
    utcOffset: 11, // AEDT
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1279,
  },
  {
    round: 2,
    country: "China",
    officialName: "FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2026",
    circuit: "Shanghai International Circuit",
    city: "Shanghai",
    dates: "13 - 15 Mar",
    raceDate: "Mar 15",
    hasSprint: true,
    slug: "china",
    utcOffset: 8,
    raceStartLocal: "15:00",
    qualiStartLocal: "15:00",
    sprintStartLocal: "11:00",
    meetingId: 1280,
  },
  {
    round: 3,
    country: "Japan",
    officialName: "FORMULA 1 ARAMCO JAPANESE GRAND PRIX 2026",
    circuit: "Suzuka International Racing Course",
    city: "Suzuka",
    dates: "27 - 29 Mar",
    raceDate: "Mar 29",
    hasSprint: false,
    slug: "japan",
    utcOffset: 9,
    raceStartLocal: "14:00",
    qualiStartLocal: "15:00",
    meetingId: 1281,
  },
  {
    round: 4,
    country: "Bahrain",
    officialName: "FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2026",
    circuit: "Bahrain International Circuit",
    city: "Sakhir",
    dates: "10 - 12 Apr",
    raceDate: "Apr 12",
    hasSprint: false,
    slug: "bahrain",
    utcOffset: 3,
    raceStartLocal: "18:00",
    qualiStartLocal: "19:00",
    cancelled: true,
  },
  {
    round: 5,
    country: "Saudi Arabia",
    officialName: "FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2026",
    circuit: "Jeddah Corniche Circuit",
    city: "Jeddah",
    dates: "17 - 19 Apr",
    raceDate: "Apr 19",
    hasSprint: false,
    slug: "saudi-arabia",
    utcOffset: 3,
    raceStartLocal: "20:00",
    qualiStartLocal: "20:00",
    cancelled: true,
  },
  {
    round: 6,
    country: "Miami",
    officialName: "FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2026",
    circuit: "Miami International Autodrome",
    city: "Miami",
    dates: "01 - 03 May",
    raceDate: "May 3",
    hasSprint: true,
    slug: "miami",
    utcOffset: -4, // EDT
    raceStartLocal: "16:00",
    qualiStartLocal: "16:00",
    sprintStartLocal: "12:00",
    meetingId: 1284,
  },
  {
    round: 7,
    country: "Canada",
    officialName: "FORMULA 1 LENOVO GRAND PRIX DU CANADA 2026",
    circuit: "Circuit Gilles-Villeneuve",
    city: "Montréal",
    dates: "22 - 24 May",
    raceDate: "May 24",
    hasSprint: true,
    slug: "canada",
    utcOffset: -4,
    raceStartLocal: "16:00",
    qualiStartLocal: "16:00",
    sprintStartLocal: "12:00",
    meetingId: 1285,
  },
  {
    round: 8,
    country: "Monaco",
    officialName: "FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026",
    circuit: "Circuit de Monaco",
    city: "Monte Carlo",
    dates: "05 - 07 Jun",
    raceDate: "Jun 7",
    hasSprint: false,
    slug: "monaco",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1286,
  },
  {
    round: 9,
    country: "Barcelona-Catalunya",
    officialName: "FORMULA 1 MSC CRUISES GRAN PREMIO DE BARCELONA-CATALUNYA 2026",
    circuit: "Circuit de Barcelona-Catalunya",
    city: "Barcelona",
    dates: "12 - 14 Jun",
    raceDate: "Jun 14",
    hasSprint: false,
    slug: "spain",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1287,
    f1Slug: "barcelona-catalunya",
  },
  {
    round: 10,
    country: "Austria",
    officialName: "FORMULA 1 LENOVO AUSTRIAN GRAND PRIX 2026",
    circuit: "Red Bull Ring",
    city: "Spielberg",
    dates: "26 - 28 Jun",
    raceDate: "Jun 28",
    hasSprint: false,
    slug: "austria",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1288,
  },
  {
    round: 11,
    country: "Great Britain",
    officialName: "FORMULA 1 PIRELLI BRITISH GRAND PRIX 2026",
    circuit: "Silverstone Circuit",
    city: "Silverstone",
    dates: "03 - 05 Jul",
    raceDate: "Jul 5",
    hasSprint: true,
    slug: "great-britain",
    utcOffset: 1, // BST
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    sprintStartLocal: "12:00",
    meetingId: 1289,
  },
  {
    round: 12,
    country: "Belgium",
    officialName: "FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2026",
    circuit: "Circuit de Spa-Francorchamps",
    city: "Spa-Francorchamps",
    dates: "17 - 19 Jul",
    raceDate: "Jul 19",
    hasSprint: false,
    slug: "belgium",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1290,
  },
  {
    round: 13,
    country: "Hungary",
    officialName: "FORMULA 1 AWS HUNGARIAN GRAND PRIX 2026",
    circuit: "Hungaroring",
    city: "Budapest",
    dates: "24 - 26 Jul",
    raceDate: "Jul 26",
    hasSprint: false,
    slug: "hungary",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1291,
  },
  {
    round: 14,
    country: "Netherlands",
    officialName: "FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2026",
    circuit: "Circuit Zandvoort",
    city: "Zandvoort",
    dates: "21 - 23 Aug",
    raceDate: "Aug 23",
    hasSprint: true,
    slug: "netherlands",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    sprintStartLocal: "12:00",
    meetingId: 1292,
  },
  {
    round: 15,
    country: "Italy",
    officialName: "FORMULA 1 PIRELLI GRAN PREMIO D'ITALIA 2026",
    circuit: "Autodromo Nazionale Monza",
    city: "Monza",
    dates: "04 - 06 Sep",
    raceDate: "Sep 6",
    hasSprint: false,
    slug: "italy",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1293,
  },
  {
    round: 16,
    country: "Spain (Madrid)",
    officialName: "FORMULA 1 TAG HEUER GRAN PREMIO DE ESPAÑA 2026",
    circuit: "Circuito de Madrid Jarama-RACE",
    city: "Madrid",
    dates: "11 - 13 Sep",
    raceDate: "Sep 13",
    hasSprint: false,
    slug: "spain-madrid",
    utcOffset: 2,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1294,
    f1Slug: "spain",
  },
  {
    round: 17,
    country: "Azerbaijan",
    officialName: "FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX 2026",
    circuit: "Baku City Circuit",
    city: "Baku",
    dates: "24 - 26 Sep",
    raceDate: "Sep 26",
    hasSprint: false,
    slug: "azerbaijan",
    utcOffset: 4,
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1295,
  },
  {
    round: 18,
    country: "Singapore",
    officialName: "FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND PRIX 2026",
    circuit: "Marina Bay Street Circuit",
    city: "Singapore",
    dates: "09 - 11 Oct",
    raceDate: "Oct 11",
    hasSprint: true,
    slug: "singapore",
    utcOffset: 8,
    raceStartLocal: "20:00",
    qualiStartLocal: "21:00",
    sprintStartLocal: "17:00",
    meetingId: 1296,
  },
  {
    round: 19,
    country: "United States",
    officialName: "FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX 2026",
    circuit: "Circuit of The Americas",
    city: "Austin",
    dates: "23 - 25 Oct",
    raceDate: "Oct 25",
    hasSprint: false,
    slug: "united-states",
    utcOffset: -5, // CDT
    raceStartLocal: "15:00",
    qualiStartLocal: "16:00",
    meetingId: 1297,
  },
  {
    round: 20,
    country: "Mexico",
    officialName: "FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026",
    circuit: "Autódromo Hermanos Rodríguez",
    city: "Mexico City",
    dates: "30 Oct - 01 Nov",
    raceDate: "Nov 1",
    hasSprint: false,
    slug: "mexico",
    utcOffset: -6,
    raceStartLocal: "14:00",
    qualiStartLocal: "15:00",
    meetingId: 1298,
  },
  {
    round: 21,
    country: "Brazil",
    officialName: "FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAULO 2026",
    circuit: "Autódromo José Carlos Pace",
    city: "São Paulo",
    dates: "06 - 08 Nov",
    raceDate: "Nov 8",
    hasSprint: false,
    slug: "brazil",
    utcOffset: -3,
    raceStartLocal: "14:00",
    qualiStartLocal: "15:00",
    meetingId: 1299,
  },
  {
    round: 22,
    country: "Las Vegas",
    officialName: "FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026",
    circuit: "Las Vegas Strip Circuit",
    city: "Las Vegas",
    dates: "19 - 21 Nov",
    raceDate: "Nov 21",
    hasSprint: false,
    slug: "las-vegas",
    utcOffset: -8,
    raceStartLocal: "20:00",
    qualiStartLocal: "20:00",
    meetingId: 1300,
  },
  {
    round: 23,
    country: "Qatar",
    officialName: "FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026",
    circuit: "Lusail International Circuit",
    city: "Lusail",
    dates: "27 - 29 Nov",
    raceDate: "Nov 29",
    hasSprint: false,
    slug: "qatar",
    utcOffset: 3,
    raceStartLocal: "19:00",
    qualiStartLocal: "21:00",
    meetingId: 1301,
  },
  {
    round: 24,
    country: "Abu Dhabi",
    officialName: "FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX 2026",
    circuit: "Yas Marina Circuit",
    city: "Abu Dhabi",
    dates: "04 - 06 Dec",
    raceDate: "Dec 6",
    hasSprint: false,
    slug: "abu-dhabi",
    utcOffset: 4,
    raceStartLocal: "17:00",
    qualiStartLocal: "18:00",
    meetingId: 1302,
  },
];

export const TRIGGER_TYPES: TriggerType[] = [
  { id: "schedule", label: "#インスタ定型文スケジュール", sessionName: "SCHEDULE" },
  { id: "sprint_qualifying", label: "#インスタ定型文スプリント予選", sessionName: "SPRINT QUALIFYING", sprintOnly: true },
  { id: "sprint", label: "#インスタ定型文スプリント", sessionName: "SPRINT", sprintOnly: true },
  { id: "qualifying", label: "#インスタ定型文予選", sessionName: "QUALIFYING" },
  { id: "race", label: "#インスタ定型文レース", sessionName: "RACE" },
];

export const F1_2025_CALENDAR = F1_2026_CALENDAR;
